spring:
  resources:
    static-locations: classpath:/public/,classpath:/static/

  datasource:
    url: jdbc:derby:../derby
    username: PUBLIC
    password:
  jpa:
    open-in-view: false

resourceBootstrapCSS: https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css
resourceBootstrapJS: https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js
resourceJQueryJS: https://code.jquery.com/jquery-3.5.1.min.js
resourcePopperJS: https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js
