# suppress inspection "UnusedProperty" for whole file
spring:
  resources:
    static-locations: classpath:/public/,classpath:/static/

  datasource:
    url: jdbc:derby:../derby
    username: PUBLIC
    password:
  jpa:
    open-in-view: false

resourceBootstrapCSS: /bootstrap-4.6.0.min.css
resourceBootstrapJS: /bootstrap-4.6.0.min.js
resourceJQueryJS: /jquery-3.5.1.min.js
resourcePopperJS: /popper-1.16.1.min.js
